# Info for connecting to the orchestrator API.
# All attributes required.
orchestrator:
  host: 192.168.36.129
  port: 4000
  username: dbaapi
  password: dbaapiusersecret

# Defaults if none provided on command line.
defaults:
  cluster: mycluster

# These are particular to the auto-master-writer.py script.
auto_master_writer:
  # Number of checks that have to occur in the same state before the master is
  # automatically set as a writer.
  check_threshold: 3
  # Number of seconds between checks.
  interval_seconds: 5
